inputs:
    input_folder: "C:/Regional Plan ABM3 OMC"

parameters:
    base_year: 2022
    scen_year: 2035

    # carshare
    population_density_threshold: 17
    high_density_mobility_hub_carshare_participation : 0.02
    low_density_mobility_hub_carshare_participation : 0.005
    college_carshare_participation : 0.02
    military_carshare_participation : 0.02
    daily_vmt_reduction_carshare : 7

    # vanpool
    c_ivt: -0.016
    avg_vanpool_occupancy: 0.8
    pct_work_trips_over_50mi: 2.7
    sov_am_time_core_name: "SOV_NT_H_TIME__AM"
    hov_am_time_core_name: "HOV3_H_TIME__AM"    
    military_base_taz: [4341, 4392, 4047, 2200, 2279, 2159, 143]
    abm_version: "ABM3"
